CREATE TABLE logistics(
D_ID INT(10) NOT NULL PRIMARY KEY,
R_Loc VARCHAR(100) NOT NULL,
O_ID INT(10) NOT NULL,
S_ID INT(10) NOT NULL,
S_Loc VARCHAR(100) NOT NULL);


CREATE TABLE employee (
Emp_ID INT(10) NOT NULL PRIMARY KEY,
Emp_First_Name VARCHAR(30) NOT NULL,
Emp_Last_Name VARCHAR(30) NOT NULL,
Contact_Num varchar(13)  NOT NULL,
Role VARCHAR(50) NOT NULL
);

CREATE TABLE orders(
O_ID INT(10) NOT NULL PRIMARY KEY,
P_ID INT(10) NOT NULL,
Quantity INT(6) NOT NULL,
Price FLOAT(7,2) NOT NULL,
O_Total FLOAT(7,2) NOT NULL,
S_ID INT(10)
);

CREATE TABLE stores(
S_ID INT(10) PRIMARY KEY,
S_Name VARCHAR(20) NOT NULL,
Contact_Num varchar(13) NOT NULL,
S_Loc varchar(100) NOT NULL 
);


CREATE TABLE products(
P_ID INT(10) NOT NULL PRIMARY KEY,
P_Name varchar(20) NOT NULL,
Price Float(7,2) NOT NULL,
P_Quantity INT(6) NOT NULL
);