LOAD DATA LOCAL INFILE 'D:/database csv/PRODUCTS.CSV'
INTO TABLE PRODUCTS
FIELDS TERMINATED BY ','
IGNORE 1 LINES
(P_ID, P_Name, Price, P_Quantity);

LOAD DATA LOCAL INFILE 'D:/database csv/ORDERS.CSV'
INTO TABLE orders
FIELDS TERMINATED BY ','
IGNORE 1 LINES
(O_ID,P_ID,Quantity,Price,O_Total,S_ID);


LOAD DATA LOCAL INFILE 'D:/database csv/STORES.CSV'
INTO TABLE stores
FIELDS TERMINATED BY ','
IGNORE 1 LINES
(S_ID, S_Name, Contact_Num, S_Loc);

LOAD DATA LOCAL INFILE 'D:/database csv/LOGISTICS.CSV'
INTO TABLE logistics
FIELDS TERMINATED BY ','
IGNORE 1 LINES
(D_ID, R_Loc, O_ID, S_ID, S_Loc);

LOAD DATA LOCAL INFILE 'D:/database csv/EMPLOYEE.CSV'
INTO TABLE employee
FIELDS TERMINATED BY ','
IGNORE 1 LINES
(Emp_ID, Emp_First_Name, Emp_Last_Name, Contact_Num, Role);